# Generated by Django 3.1.3 on 2020-11-24 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0002_auto_20201122_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Reservation',
        ),
    ]
