# Generated by Django 3.1.3 on 2020-12-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0003_auto_20201124_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservation',
            new_name='Message',
        ),
    ]
