# Generated by Django 3.1.3 on 2020-12-01 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0004_auto_20201201_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Reservation',
        ),
    ]
